specVersion: 0.2.0
name: parascan-subql-starter
version: 1.0.0
description: subql starter for parascan
repository: "https://github.com/parascan/parascan-subql-starter"
schema:
  file: ./schema.graphql

network:
  endpoint: "wss://sirius-22.origin-trail.network"
  genesisHash: "0xe7e0962324a3b86c83404dbea483f25fb5dab4c224791c81b756cfc948006174"

dataSources:
  - kind: substrate/Runtime
    startBlock: 1
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: balances
            method: Transfer        
        - handler: handleBlock
          kind: substrate/BlockHandler
        - handler: handleEvent
          kind: substrate/EventHandler
        - handler: handleCall
          kind: substrate/CallHandler
